### ISSUE TITLE
Add some examples of plugins reimplemented in Lua

### ISSUE THREAD

**Issue by alexherbo2** [gustavo-hms/luar#10]
It could be nice to have a few examples of plugins in Luar or dedicated repositories with a link to them or with the topics [`#kakoune #plugin #luar`].

[`#kakoune #plugin #luar`]: https://github.com/search?q=topic:kakoune+topic:plugin+topic:luar

**Comment by gustavo-hms** [comment]
Hi, @alexherbo2 !

It's a nice idea. However, excluding me and [Teddy](https://github.com/TeddyDD/kakoune-dotfiles/blob/master/private/yaml-indent.kak), I'm not aware of anyone using this plugin. And my usage is mostly related to many small handy stuff, I didn't write a full plugin.

Anyway, I can put somewhere some of this stuff I've coded. Do you think the best place is the README or it's better to create a wiki or something?

I can also make a call to the community to see if others can bring some more examples of real-world usage.

**Comment by alexherbo2** [comment]
A dedicated repository could be nice to see the full thing.

**Comment by gustavo-hms** [comment]
Ok! [It's done](https://github.com/search?q=topic%3Akakoune+topic%3Aplugin+topic%3Alua). Now what's missing is inviting others to also publish their scripts.
