### ISSUE TITLE
Wrap code into a module

### ISSUE THREAD

**Issue by alexherbo2** [gustavo-hms/luar#7]

**Comment by gustavo-hms** [comment]
I've seen people talking about this module feature, but, as I don't follow the project closely, and it seems the documentation about it is scarce, I don't fully understand what it is for. Would you mind to give me a brief introduction to the concept? Specially, could you please explain why it would be useful for `luar` to use this feature?

**Comment by alexherbo2** [comment]
You can understand a module as an init function.  The files are sourced, but their content not executed until you call the require module command.  It is useful to speed up the loading or when modules have dependencies, because you call the require commands in your kakrc once all the files in your autoload have been sourced.  You also have hooks to execute commands once a module has been loaded.

**Comment by gustavo-hms** [comment]
Fine. I'm gonna do it soon.

**Comment by gustavo-hms** [comment]
That's it. See if everything is OK, please.
